agents:
  finops_pilot:
    name: FinOps Pilot
    description: AWS cost optimization and cloud resource management
    url: https://replit.com/@ilyacantor/FinOpsPilot
    consumes:
      - aws_resource
      - cloud_cost
      - cloud_usage
      - cloud_invoice
    key_metrics:
      - resource_id
      - instance_type
      - vcpus
      - memory
      - db_engine
      - cpu_utilization
      - memory_utilization
      - network_in
      - network_out
      - db_connections
      - monthly_cost
      - service_category
    color: "#9333ea"
  
  revops_pilot:
    name: RevOps Pilot
    description: Revenue operations and sales pipeline optimization (BANT validation, Pipeline health)
    consumes:
      - account
      - opportunity
      - health
      - usage
    key_metrics:
      - account_name
      - revenue
      - amount
      - close_date
      - stage
      - health_score
      - last_login_days
      - sessions_30d
    color: "#3b82f6"
